keys:
  - &admin_luna age1dm8jqk7u9mcfg0wgcs0fllju33lp2wk706xdf9s0nrcdhrvseqsshh302h
  - &server_striker age1v023jsaemhdyp3lvs48faxnd2rmypv926vv7gc9e0xcccnu5yvgq366dx4
  - &server_scrapy age1p6d96298ngyvsagg0usllr5c7u7z376vdu0l2ydenxkprdwxrpss0lcred
creation_rules:
  - path_regex: hosts/striker-eureka/token
    key_groups:
    - age:
      - *admin_luna
      - *server_striker
  - path_regex: hosts/scrappy/token
    key_groups:
    - age: 
      - *admin_luna
      - *server_scrapy

    
